
name: VMPE-Action
main: bansystem\BanSystem
version: 1.0.0
author: Zeao
api: [3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.1, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
description: A ban system for VoidMinerPE.
