
name: BanSystem
main: bansystem\BanSystem
version: 1.0.3
author: xXSuperFrostyXx, randy128gamer
api: [3.0.0, 4.0.0]
description: A ban system that allows to temporarily/permanently ban/mute/block and kick players/IP address.
